#make karyotype from faidx file with white
awk '{print "chr - "$1" "$1" 0 "$2" black"}' 1033.l0.fa.fai >> chr.kar
awk '{print "chr - "$1" "$1" 0 "$2" white"}' E.bromicola.renamed.fna.fai >> chr.kar
#You can specify colours as a hue, ranging from 0 to 360. Our reference (AWRI2804) has 9 contigs, so our hue ‘steps’ will be 360/9 = 40. The query (CBS2499) we’ll just colour white.
awk '{hue=sprintf("%03d", h); print "chr - "$1" "$1" 0 "$2" hue"hue; h+=12;}' 1033.l0.fa.fai >  chr.kar


#The links that circos plots will simply be the alignments that were generated by nucmer. You can view them with show-coords. We need to convert the format for circos so that the columns are:
#refContig start stop queryContig start stop z-depth

#We need to sort the alignments by alignment length so that we can apply a “z-depth”. Giving smaller alignments larger z-depths ensures that they are plotted on top of larger ones, which is better for overall clarity.
show-coords -TH 1033.bromicola.mdelta | sort -k5,5nr | awk '{z+=1;print $8"\t"$1"\t"$2"\t"$9"\t"$3"\t"$4"\tz="z}' > links.tsv
